// 検索対象の製品情報と、それに紐づく適合表のカラム情報をオプションタイプ別に定義
export const PRODUCTS_DATA = {
    'FreeTVing': {
        name: 'フリーテレビング/テレナビング',
        productKey: 'televing',
        optionFlows: {
            'maker': {
                processType: 'maker_process',
                pdf_paths: {
                    'トヨタ': '../../pdf/products/TVing/TVing_New_m_toyota.pdf',
                    'レクサス': '../../pdf/products/TVing/TVing_New_m_lexus.pdf',
                    'ニッサン': '../../pdf/products/TVing/TVing_New_m_nissan.pdf',
                    'ホンダ': '../../pdf/products/TVing/TVing_New_m_honda.pdf',
                    'マツダ': '../../pdf/products/TVing/TVing_New_m_mazda.pdf',
                    'スバル': '../../pdf/products/TVing/TVing_New_m_subaru.pdf',
                    'スズキ': '../../pdf/products/TVing/TVing_New_m_suzuki.pdf',
                    'ダイハツ': '../../pdf/products/TVing/TVing_New_m_daihatsu.pdf',
                    'ミツビシ': '../../pdf/products/TVing/TVing_New_m_mitsubishi.pdf'
                },
                header: [
                    { label: '車両情報', subHeaders: [
                        { key: 'car_model', label: '車名' },
                        { key: 'print_date', label: '年式' },
                        { key: 'model_number', label: '型式' },
                        { key: 'specification', label: '仕様' },
                    ]},
                    { label: 'フリーテレビング', subHeaders: [
                        { key: 'ft_auto_type', label: 'オートタイプ',
                            priceKeys: { excl: 'ft_auto_price_excl_tax', incl: 'ft_auto_price_incl_tax' },
                            option: {nav: 'ft_led_sh_st_navigation_control', vehicle_pos: 'ft_led_sh_st_vehicle_position'}
                         },
                        { key: 'ft_led_switch_type', label: 'LEDスイッチ切替タイプ', 
                            priceKeys: { excl: 'ft_led_price_excl_tax', incl: 'ft_led_price_incl_tax' },
                            option: {nav: 'ft_led_sh_st_navigation_control', vehicle_pos: 'ft_led_sh_st_vehicle_position', dvd: 'ft_led_sh_st_dvd_playback'}
                        },
                        { key: 'ft_service_hole_switch_type', label: 'サービスホールスイッチ切替タイプ',
                            priceKeys: { excl: 'ft_service_hole_price_excl_tax', incl: 'ft_service_hole_price_incl_tax' },
                            option: {nav: 'ft_led_sh_st_navigation_control', vehicle_pos: 'ft_led_sh_st_vehicle_position', dvd: 'ft_led_sh_st_dvd_playback'}
                        },
                        { key: 'ft_steering_switch_type', label: 'ステアリングスイッチ切替タイプ', 
                            priceKeys: { excl: 'ft_steering_price_excl_tax', incl: 'ft_steering_price_incl_tax' },
                            option: {nav: 'ft_led_sh_st_navigation_control', vehicle_pos: 'ft_led_sh_st_vehicle_position', dvd: 'ft_led_sh_st_dvd_playback'}
                        },
                    ]},
                    { label: 'テレナビング', subHeaders: [
                        { key: 'nav_product_number', label: 'LEDスイッチ切替タイプ',
                            priceKeys: { excl: 'nav_price_excl_tax', incl: 'nav_price_incl_tax' }, option:{dvd: 'nav_dvd_playback_2'} },
                        { key: 'nav_product_number_2', label: 'nav_col_2',
                            priceKeys: { excl: 'nav_price_excl_tax_2', incl: 'nav_price_incl_tax_2' }, option:{dvd: 'nav_dvd_playback_2'} },
                    ]},
                    { label: '注意事項', subHeaders: [
                        { key: 'notes', label: '備考' }
                    ]}
                ]
            },
            'dealer': {
                processType: 'dealer_process',
                pdf_paths: {
                    'トヨタ': '../../pdf/products/TVing/TVing_New_d_toyota.pdf',
                    'レクサス': '../../pdf/products/TVing/TVing_New_d_lexus.pdf',
                    'ニッサン': '../../pdf/products/TVing/TVing_New_d_nissan.pdf',
                    'ホンダ': '../../pdf/products/TVing/TVing_New_d_honda.pdf',
                    'マツダ': '../../pdf/products/TVing/TVing_New_d_mazda.pdf',
                    'スバル': '../../pdf/products/TVing/TVing_New_d_subaru.pdf',
                    'スズキ': '../../pdf/products/TVing/TVing_New_d_suzuki.pdf',
                    'ダイハツ': '../../pdf/products/TVing/TVing_New_d_daihatsu.pdf',
                    'ミツビシ': '../../pdf/products/TVing/TVing_New_d_mitsubishi.pdf'
                },
                header: [
                    { label: 'モニター情報', subHeaders: [
                        { key: 'year', label: 'モデル年' },
                        { key: 'monitor_number', label: 'モニター型番' },
                        { key: 'specification', label: '特徴' },
                    ]},
                    { label: 'フリーテレビング', subHeaders: [
                        { key: 'ft_auto_type', label: 'オートタイプ',
                            priceKeys: { excl: 'ft_auto_price_excl_tax', incl: 'ft_auto_price_incl_tax' },
                            option: {nav: 'ft_auto_navigation_control', vehicle_pos: 'ft_auto_vehicle_position'}
                         },
                        { key: 'ft_led_switch_type', label: 'LEDスイッチ切替タイプ', 
                            priceKeys: { excl: 'ft_led_price_excl_tax', incl: 'ft_led_price_incl_tax' },
                            option: {nav: 'ft_led_sh_st_navigation_control', vehicle_pos: 'ft_led_sh_st_vehicle_position', dvd: 'ft_led_sh_st_dvd_playback'}
                        },
                        { key: 'ft_service_hole_switch_type', label: 'サービスホールスイッチ切替タイプ',
                            priceKeys: { excl: 'ft_service_hole_price_excl_tax', incl: 'ft_service_hole_price_incl_tax' },
                            option: {nav: 'ft_led_sh_st_navigation_control', vehicle_pos: 'ft_led_sh_st_vehicle_position', dvd: 'ft_led_sh_st_dvd_playback'}
                        }
                    ]},
                    { label: 'テレナビング', subHeaders: [
                        { key: 'nav_product_number', label: 'LEDスイッチ切替タイプ',
                            priceKeys: { excl: 'nav_price_excl_tax', incl: 'nav_price_incl_tax' }, option:{dvd: 'nav_dvd_playback_2'} },
                        { key: 'nav_product_number_2', label: 'nav_col_2',
                            priceKeys: { excl: 'nav_price_excl_tax_2', incl: 'nav_price_incl_tax_2' }, option:{dvd: 'nav_dvd_playback_2'} },
                    ]},
                    { label: '注意事項', subHeaders: [
                        { key: 'notes', label: '備考' }
                    ]}
                ]
            }
        }
    },
    'Magicone': {
        name: 'バックカメラ接続ユニット',
        productKey: 'magicone_un',
        optionFlows: {
            'maker': {
                processType: 'maker_process',
                pdf_paths: {
                    'トヨタ': '../../pdf/products/MAGICONE/magicone_c_m_toyota.pdf',
                    'レクサス': '',
                    'ニッサン': '../../pdf/products/MAGICONE/magicone_c_m_nissan.pdf',
                    'ホンダ': '../../pdf/products/MAGICONE/magicone_c_m_honda.pdf',
                    'マツダ': '../../pdf/products/MAGICONE/magicone_c_m_mazda.pdf',
                    'スバル': '../../pdf/products/MAGICONE/magicone_c_m_subaru.pdf',
                    'スズキ': '../../pdf/products/MAGICONE/magicone_c_m_suzuki.pdf',
                    'ダイハツ': '../../pdf/products/MAGICONE/magicone_c_m_daihatsu.pdf',
                    'ミツビシ': '../../pdf/products/MAGICONE/magicone_c_m_mitsubishi.pdf'
                },
                header: [
                    { label: '車両情報', subHeaders: [
                        { key: 'car_model', label: '車名' },
                        { key: 'print_date', label: '年式' },
                        { key: 'model_number', label: '型式' },
                        { key: 'specification', label: '仕様' },
                    ]},
                    { label: 'バックカメラ接続ユニット', subHeaders: [
                        { key: 'un_product_number_1', label: '品番１',
                            priceKeys: { excl: 'un_price_excl_tax_1', incl: 'un_price_incl_tax_1' },
                         },
                        { key: 'un_product_number_2', label: '品番2', 
                            priceKeys: { excl: 'un_price_excl_tax_2', incl: 'un_price_incl_tax_2' },
                        },
                    ]},
                    { label: '注意事項', subHeaders: [
                        { key: 'notes', label: '備考' }
                    ]}
                ]
            },
            'dealer': {
                processType: 'dealer_process',
                pdf_paths: {
                    'トヨタ': '../../pdf/products/MAGICONE/magicone_c_d_toyota.pdf',
                    'レクサス': '',
                    'ニッサン': '../../pdf/products/MAGICONE/magicone_c_d_nissan.pdf',
                    'ホンダ': '../../pdf/products/MAGICONE/magicone_c_d_honda.pdf',
                    'マツダ': '../../pdf/products/MAGICONE/magicone_c_d_mazda.pdf',
                    'スバル': '',
                    'スズキ': '../../pdf/products/MAGICONE/magicone_c_d_suzuki.pdf',
                    'ダイハツ': '../../pdf/products/MAGICONE/magicone_c_d_daihatsu.pdf',
                    'ミツビシ': '../../pdf/products/MAGICONE/magicone_c_d_mitsubishi.pdf'
                },
                header: [
                    { label: '車両情報', subHeaders: [
                        { key: 'year', label: 'モデル年' },
                        { key: 'monitor_number', label: 'モニター型番' },
                        { key: 'specification', label: '仕様' },
                    ]},
                    { label: 'バックカメラ接続ユニット', subHeaders: [
                        { key: 'product_number_1', label: '品番１',
                            priceKeys: { excl: 'un_price_excl_tax_1', incl: 'un_price_incl_tax_1' },
                         }                        
                    ]},
                    { label: '注意事項', subHeaders: [
                        { key: 'notes', label: '備考' }
                    ]}
                ]
            },
        }
    },
};

export const CAR_TYPE = {
    "トヨタ": [
        "bB",
        "bz4x",
        "C-HR",
        "GRカローラ",
        "GRヤリス",
        "RAV4",
        "Will CYPHA",
        "アイシス",
        "アクア",
        "アリオン",
        "アリスト",
        "アルテッツァ",
        "アルファード",
        "アレックス",
        "イスト",
        "イプサム",
        "ヴァンガード",
        "ウィッシュ",
        "ヴィッツ",
        "ウインダム",
        "ヴェルファイア",
        "ヴェロッサ",
        "ヴォクシー",
        "エスクァイア",
        "エスティマ",
        "オーパ",
        "オーリス",
        "オリジン",
        "ガイア",
        "カムリ",
        "カムリグラシア",
        "カリーナ",
        "カルディナ",
        "カローラアクシオ",
        "カローラクロス",
        "カローラスパシオ",
        "カローラスポーツ",
        "カローラセダン",
        "カローラツーリング",
        "カローラフィールダー",
        "カローラランクス",
        "カローラルミオン",
        "クラウン",
        "クラウンエステート",
        "クラウンクロスオーバー",
        "クラウンスポーツ",
        "クラウンセダン",
        "クラウンマジェスタ",
        "グランエース",
        "グランドハイエース",
        "グランビア",
        "クルーガー",
        "コロナプレミオ",
        "サイ",
        "サクシード",
        "シエンタ",
        "スープラ",
        "セリカ",
        "セルシオ",
        "センチュリー",
        "タウンエースノア",
        "ツーリングハイエース",
        "デュエット",
        "ナディア",
        "ノア",
        "ハイエース",
        "ハイエースコミューター",
        "ハイラックス",
        "パッソ",
        "パッソセッテ",
        "ハリアー",
        "ファンカーゴ",
        "プラッツ",
        "プリウス",
        "プリウスPHEV",
        "プリウスPHV",
        "プリウスα",
        "ブレイド",
        "ブレビス",
        "プレミオ",
        "プログレ",
        "プロボックス",
        "ベルタ",
        "ポルテ",
        "マークⅡ",
        "マークX",
        "ミライ",
        "ヤリス",
        "ヤリスクロス",
        "ライズ",
        "ライトエースノア",
        "ラウム",
        "ラクティス",
        "ラッシュ",
        "ランドクルーザー",
        "ランドクルーザー250",
        "ランドクルーザー300",
        "ランドクルーザーシグナス",
        "ランドクルーザープラド",
        "ルーミー",
        "レジアス",
        "レジアスエース"
    ],
    "レクサス": [
        "CT",
        "ES",
        "GS",
        "GS F",
        "GX",
        "HS",
        "IS",
        "IS C",
        "IS F",
        "LBX",
        "LC",
        "LFA",
        "LM",
        "LS",
        "LX",
        "NX",
        "RC",
        "RC F",
        "RX",
        "RZ",
        "SC",
        "UX",
        "UX300e"
    ],
    "ニッサン": [
        "GT-R",
        "アベニール",
        "アリア",
        "ウイングロード",
        "エクストレイル",
        "エルグランド",
        "オッティ",
        "キャラバン",
        "キューブ",
        "グロリア",
        "サクラ",
        "サニー",
        "シーマ",
        "ジューク",
        "シルビア",
        "スカイライン",
        "ステージア",
        "セドリック",
        "セフィーロ",
        "セレナ",
        "ダットサン",
        "ティアナ",
        "ティーダ",
        "ティーダラティオ",
        "ティーノ",
        "デュアリス",
        "ノート",
        "ノートオーラ",
        "バサラ",
        "フーガ",
        "フェアレディZ",
        "プリメーラ",
        "ブルーバード",
        "プレサージュ",
        "マーチ",
        "ムラーノ",
        "ラフェスタ",
        "リーフ",
        "リバティ",
        "ルークス"
    ],
    "ホンダ": [
        "CR-V",
        "CR-Z",
        "Honda e",
        "HR-V",
        "MDX",
        "NSX",
        "N-WGN",
        "S2000",
        "S-MX",
        "ZR-V",
        "アコード",
        "インサイト",
        "インスパイア",
        "インテグラ",
        "ヴェゼル",
        "エアウェイブ",
        "エディックス",
        "エリシオン",
        "オデッセイ",
        "オルティア",
        "グレイス",
        "クロスロード",
        "ジェイド",
        "シビック",
        "シビック TYPE R",
        "シャトル",
        "ステップワゴン",
        "ステップワゴン Modulo X",
        "ステップワゴン スパーダ",
        "ストリーム",
        "ゼスト",
        "フィット",
        "フィットシャトル",
        "フリード",
        "フリード Modulo X",
        "フリード＋",
        "フリードスパイク",
        "モビリオ",
        "モビリオスパイク",
        "ライフ",
        "ラグレイト",
        "レジェンド"
    ],
    "ミツビシ": [
        "ekクロスEV",
        "eKスポーツ",
        "eKワゴン",
        "I",
        "RVR",
        "アウトランダー",
        "エアトレック",
        "エクリプスクロス",
        "ギャランフォルティス",
        "グランディス",
        "コルト",
        "シャリオグランディス",
        "タウンボックス",
        "ディオン",
        "ディグニティ",
        "デリカD:2",
        "デリカD:5",
        "トッポ",
        "トライトン",
        "パジェロ",
        "パジェロイオ",
        "パジェロミニ",
        "プラウディア",
        "ミラージュ",
        "ランサー",
        "ランサーエボリューション",
        "ランサーセディア"
    ],
    "スバル": [
        "WRX S4",
        "WRX",
        "XV",
        "インプレッサ",
        "インプレッサ G4",
        "インプレッサ アネシス",
        "インプレッサ スポーツ",
        "エクシーガ",
        "クロストレック",
        "シフォン",
        "ジャスティ",
        "フォレスター",
        "レヴォーグ",
        "レヴォーグ レイバック",
        "レガシィ B4",
        "レガシィ アウトバック",
        "レガシィ ツーリング",
        "レックス"
    ],
    "スズキ": [
        "アルト",
        "イグニス",
        "エスクード",
        "エブリィ",
        "スイフト",
        "スペーシア",
        "スペーシア カスタム",
        "スペーシア カスタムZ",
        "スペーシア ギア",
        "ソリオ",
        "ハスラー",
        "フロンクス",
        "ラパン",
        "ワゴンR",
        "ワゴンR スティングレー",
        "ワゴンR スマイル"
    ],
    "ダイハツ": [
        "アトレー",
        "アトレー7",
        "アルティス",
        "キャスト アクティバ",
        "キャスト スタイル",
        "キャスト スポーツ",
        "クー",
        "ストーリア",
        "ソニカ",
        "タフト",
        "タント",
        "タント エグゼ",
        "タント カスタム",
        "タント ファンクロス",
        "デルタ ワゴン",
        "トール",
        "パイザー",
        "ハイゼット カーゴ",
        "ハイゼット トラック",
        "ビーゴ",
        "ブーン",
        "ブーン カスタム",
        "ブーン ルミナス",
        "マックス",
        "ミラ",
        "ミラ アヴィ",
        "ミラ ココア",
        "ムーヴ",
        "ムーヴ カスタム",
        "ムーヴ キャンバス",
        "ムーヴ コンテ",
        "メビウス",
        "ロッキー"
    ],
    "マツダ": [
        "CX-3",
        "CX-30",
        "CX-5",
        "CX-60",
        "CX-7",
        "CX-8",
        "CX-80",
        "MAZDA2",
        "MAZDA3",
        "MAZDA6",
        "MPV",
        "MX-30",
        "RX-8",
        "アクセラスポーツ",
        "アクセラセダン",
        "アテンザスポーツ",
        "アテンザセダン",
        "アテンザワゴン",
        "カペラ",
        "デミオ",
        "トリビュート",
        "ビアンテ",
        "ファミリア",
        "フレアワゴン",
        "プレマシー",
        "ベリーサ",
        "ボンゴ",
        "ミレーニア",
        "ロードスター",
        "ロードスターRF"
    ]
};

export const DEALER_NAV = {
    "トヨタ": [
        { "year": "2025", "product_code": "NMZK-W75DE" },
        { "year": "2023", "product_code": "NMZN-Y73D" },
        { "year": "2023", "product_code": "NMZK-W73D" },
        { "year": "2022", "product_code": "NMZK-W72D" },
        { "year": "2018", "product_code": "NSCN-W68" },
        { "year": "2018", "product_code": "NSZN-Z68T" },
        { "year": "2018", "product_code": "NSZT-W68T" },
        { "year": "2018", "product_code": "NSZT-Y68T" },
        { "year": "2016", "product_code": "NSCD-W66" },
        { "year": "2016", "product_code": "NSZN-Z66T" },
        { "year": "2016", "product_code": "NSZT-W66T" },
        { "year": "2016", "product_code": "NSZT-Y66T" },
        { "year": "2014", "product_code": "DSZT-YB4Y" },
        { "year": "2014", "product_code": "DSZT-YC4T" },
        { "year": "2014", "product_code": "NSCP-W64" },
        { "year": "2014", "product_code": "NSZA-X64T" },
        { "year": "2014", "product_code": "NSZN-W64T" },
        { "year": "2014", "product_code": "NSZT-W64" },
        { "year": "2014", "product_code": "NSZT-Y64T" },
        { "year": "2014", "product_code": "NSZT-YA4T" },
        { "year": "2014", "product_code": "NSZT-ZA4T" },
        { "year": "2012", "product_code": "DAN-W62" },
        { "year": "2012", "product_code": "NHBA-W62G" },
        { "year": "2012", "product_code": "NHBA-X62G" },
        { "year": "2012", "product_code": "NHZD-W62G" },
        { "year": "2012", "product_code": "NHZN-X62G" },
        { "year": "2012", "product_code": "NSCP-W62" },
        { "year": "2012", "product_code": "NSLN-W62" },
        { "year": "2012", "product_code": "NSZT-W62G" },
        { "year": "2012", "product_code": "NSZT-Y62G" },
        { "year": "2011", "product_code": "NHZA-W61G" },
        { "year": "2011", "product_code": "NHZN-W61G" },
        { "year": "2011", "product_code": "NHZN-X61G" },
        { "year": "2011", "product_code": "NSCP-W61" },
        { "year": "2011", "product_code": "NSCT-W61" },
        { "year": "2011", "product_code": "NSDD-W61" },
        { "year": "2011", "product_code": "NSZT-W61G" },
        { "year": "2010", "product_code": "NHZA-W60G" },
        { "year": "2010", "product_code": "NHZN-W60G" },
        { "year": "2010", "product_code": "NHDT-W60G" },
        { "year": "2010", "product_code": "NSCN-W60" },
        { "year": "2010", "product_code": "NSDN-W60" },
        { "year": "2010", "product_code": "NSZD-W60" },
        { "year": "2010", "product_code": "NSZT-W60" },
        { "year": "2009", "product_code": "NHDT-W59" },
        { "year": "2009", "product_code": "NHDT-W59G" },
        { "year": "2009", "product_code": "NHZA-W59G" },
        { "year": "2009", "product_code": "NHZN-W59G" },
        { "year": "2009", "product_code": "NSCN-W59C" },
        { "year": "2009", "product_code": "NSDN-W59" },
        { "year": "2009", "product_code": "NSDT-W59" },
        { "year": "2008", "product_code": "NDDN-W58" },
        { "year": "2008", "product_code": "NH3N-W58" },
        { "year": "2008", "product_code": "NH3N-W58G" },
        { "year": "2008", "product_code": "NHDT-W58" },
        { "year": "2008", "product_code": "NHDT-W58G" },
        { "year": "2008", "product_code": "NHZA-W58G" },
        { "year": "2008", "product_code": "NHZP-W58S" },
        { "year": "2008", "product_code": "NHZT-W58" },
        { "year": "2008", "product_code": "NHZT-W58G" },
        { "year": "2007", "product_code": "ND3T-W57" },
        { "year": "2007", "product_code": "NDDN-W57" },
        { "year": "2007", "product_code": "NH3N-W57" },
        { "year": "2007", "product_code": "NHDA-W57G" },
        { "year": "2007", "product_code": "NHDP-W57S" },
        { "year": "2007", "product_code": "NHDT-W57" },
        { "year": "2007", "product_code": "NHDT-W57D" },
        { "year": "2007", "product_code": "NHZN-W57" },
        { "year": "2006", "product_code": "ND3T-W56" },
        { "year": "2006", "product_code": "NDDA-W56" },
        { "year": "2006", "product_code": "NDDN-W56" },
        { "year": "2006", "product_code": "NH3T-W56" },
        { "year": "2006", "product_code": "NHDN-W56" },
        { "year": "2006", "product_code": "NHDN-W56G" },
        { "year": "2006", "product_code": "NHDP-W56S" },
        { "year": "2006", "product_code": "NHXT-W56D" },
        { "year": "2005", "product_code": "ND3T-W55" },
        { "year": "2005", "product_code": "NDCN-D55" },
        { "year": "2005", "product_code": "NDCN-W55" },
        { "year": "2005", "product_code": "NDDA-W55" },
        { "year": "2005", "product_code": "NH3T-W55" },
        { "year": "2005", "product_code": "NHDN-W55G" },
        { "year": "2005", "product_code": "NHDT-W55" },
        { "year": "2005", "product_code": "NHXT-W55V" },
        { "year": "2004", "product_code": "ND3A-W54A" },
        { "year": "2004", "product_code": "ND3T-D54" },
        { "year": "2004", "product_code": "ND3T-W54" },
        { "year": "2004", "product_code": "NDCN-D54" },
        { "year": "2004", "product_code": "NDCN-W54" },
        { "year": "2004", "product_code": "NDCT-W54E" },
        { "year": "2004", "product_code": "NHCT-D54" },
        { "year": "2004", "product_code": "NHCT-W54" },
        { "year": "2004", "product_code": "NHDN-W54G" },
        { "year": "2004", "product_code": "NHDP-D54" },
        { "year": "2004", "product_code": "NHDP-W54" },
        { "year": "2004", "product_code": "NHDT-W54V" },
        { "year": "2003", "product_code": "NCMT-D53" },
        { "year": "2003", "product_code": "NCMT-W53" },
        { "year": "2003", "product_code": "ND3A-W53A" },
        { "year": "2003", "product_code": "ND3N-D53" },
        { "year": "2003", "product_code": "ND3N-W53" },
        { "year": "2003", "product_code": "NDCT-D53" },
        { "year": "2003", "product_code": "NDCT-W53" },
        { "year": "2003", "product_code": "NDCT-W53E" },
        { "year": "2003", "product_code": "NDDP-W53R" },
        { "year": "2003", "product_code": "NHDP-D53" },
        { "year": "2003", "product_code": "NHDP-W53" },
        { "year": "2003", "product_code": "NHDT-W53" },
        { "year": "2003", "product_code": "NHDT-W53M" },
        { "year": "2003", "product_code": "NVN-D53" },
        { "year": "2022", "product_code": "MM222D-Le" },
        { "year": "2003", "product_code": "GCN-W53" },
        { "year": "2002", "product_code": "NCKT-D52" },
        { "year": "2002", "product_code": "NCKT-W52" },
        { "year": "2002", "product_code": "NCMT-D52" },
        { "year": "2002", "product_code": "NCMT-W52" },
        { "year": "2002", "product_code": "ND3A-D52A" },
        { "year": "2002", "product_code": "ND3A-W52A" },
        { "year": "2002", "product_code": "ND3N-D52" },
        { "year": "2002", "product_code": "ND3N-W52" },
        { "year": "2002", "product_code": "ND3T-D52M" },
        { "year": "2002", "product_code": "ND3T-W52M" },
        { "year": "2002", "product_code": "ND3T-D52V" },
        { "year": "2002", "product_code": "ND3T-W52V" },
        { "year": "2002", "product_code": "NDDP-D52R" },
        { "year": "2002", "product_code": "NDDP-W52R" },
        { "year": "2002", "product_code": "NDKT-D52" },
        { "year": "2002", "product_code": "NDKT-W52" },
        { "year": "2002", "product_code": "NHMP-D52" },
        { "year": "2002", "product_code": "NHMP-W52" },
        { "year": "2002", "product_code": "NVN-D52" },
        { "year": "2001", "product_code": "NCN-D51" },
        { "year": "2001", "product_code": "NCN-W51" },
        { "year": "2001", "product_code": "NDP-D51R" },
        { "year": "2001", "product_code": "NDP-W51R" },
        { "year": "2001", "product_code": "NKP-D51" },
        { "year": "2001", "product_code": "NKP-Ｗ51" },
        { "year": "2001", "product_code": "NKT-D51" },
        { "year": "2001", "product_code": "NKT-W51" },
        { "year": "2001", "product_code": "NMCN-D51M" },
        { "year": "2001", "product_code": "NMCN-W51M" },
        { "year": "2001", "product_code": "NMCT-D51" },
        { "year": "2001", "product_code": "NMCT-W51" },
        { "year": "2022", "product_code": "MJ322D-L" },
        { "year": "2001", "product_code": "NMT-D51" },
        { "year": "2001", "product_code": "NMT-D51M" },
        { "year": "2001", "product_code": "NMT-W51" },
        { "year": "2001", "product_code": "NMT-W51M" },
        { "year": "2001", "product_code": "NVN-D51" },
        { "year": "2000", "product_code": "NKN-D50" },
        { "year": "2000", "product_code": "NKN-W50" },
        { "year": "2000", "product_code": "NKP-D50" },
        { "year": "2000", "product_code": "NKP-W50" },
        { "year": "2000", "product_code": "NKT-D50" },
        { "year": "2000", "product_code": "NKT-D50S" },
        { "year": "2000", "product_code": "NKT-W50" },
        { "year": "2000", "product_code": "NKT-W50S" },
        { "year": "2000", "product_code": "NMCT-D50" },
        { "year": "2000", "product_code": "NMCT-W50" },
        { "year": "2000", "product_code": "NMN-D50" },
        { "year": "2000", "product_code": "NMN-W50" },
        { "year": "2000", "product_code": "NMP-D50M" },
        { "year": "2000", "product_code": "NMP-W50M" },
        { "year": "2000", "product_code": "NMT-D50M" },
        { "year": "2000", "product_code": "NMT-W50M" },
        { "year": "2000", "product_code": "NVD-D50" },
        { "year": "1999", "product_code": "NKCN-D59" },
        { "year": "1999", "product_code": "NKCN-W59" },
        { "year": "1999", "product_code": "NKCT-D59" },
        { "year": "1999", "product_code": "NKCT-W59" },
        { "year": "1999", "product_code": "NMCT-D59" },
        { "year": "1999", "product_code": "NMCT-W59" },
        { "year": "1999", "product_code": "NMDN-D59" },
        { "year": "1999", "product_code": "NMDN-W59" }
    ],
    "ニッサン": [
        { "year": "2023", "product_code": "MJ123D-A" },
        { "year": "2023", "product_code": "MJ123D-W" },
        { "year": "2023", "product_code": "MM223D-Le" },
        { "year": "2023", "product_code": "MM223D-L" },
        { "year": "2023", "product_code": "MJ323D-W" },
        { "year": "2023", "product_code": "MJ323D-L" },
        { "year": "2023", "product_code": "MM323D-L" },
        { "year": "2023", "product_code": "MJ322D-L" },
        { "year": "2023", "product_code": "MM523D-L" },
        { "year": "2022", "product_code": "DA22J" },
        { "year": "2022", "product_code": "MJ122D-A" },
        { "year": "2022", "product_code": "MJ122D-W" },
        { "year": "2022", "product_code": "MM222D-L" },
        { "year": "2022", "product_code": "MJ322D-W" },
        { "year": "2022", "product_code": "MM522D-L" },
        { "year": "2021", "product_code": "MJ121D-A" },
        { "year": "2021", "product_code": "MJ121D-W" },
        { "year": "2021", "product_code": "MJ121D-L" },
        { "year": "2021", "product_code": "MJ321D-A" },
        { "year": "2021", "product_code": "MJ321D-W" },
        { "year": "2021", "product_code": "MJ321D-L" },
        { "year": "2021", "product_code": "MM321D-L" },
        { "year": "2021", "product_code": "MM321D-L" },
        { "year": "2021", "product_code": "MM521D-L" },
        { "year": "2020", "product_code": "MJ120D-A" },
        { "year": "2020", "product_code": "MJ120D-L" },
        { "year": "2020", "product_code": "MJ120D-W" },
        { "year": "2020", "product_code": "MJ320D-A" },
        { "year": "2020", "product_code": "MJ320D-L" },
        { "year": "2020", "product_code": "MJ320D-W" },
        { "year": "2020", "product_code": "MM320D-L" },
        { "year": "2020", "product_code": "MM320D-L" },
        { "year": "2020", "product_code": "MM520D-L" },
        { "year": "2020", "product_code": "MM520D-L" },
        { "year": "2019", "product_code": "MJ119D-A" },
        { "year": "2019", "product_code": "MJ119D-W" },
        { "year": "2019", "product_code": "MM319D-A" },
        { "year": "2019", "product_code": "MM319D-W" },
        { "year": "2019", "product_code": "MM319D-L" },
        { "year": "2019", "product_code": "MM319D-L" },
        { "year": "2019", "product_code": "MM519D-L" },
        { "year": "2019", "product_code": "MM519D-L" },
        { "year": "2019", "product_code": "MM519D-L" },
        { "year": "2018", "product_code": "MJE18D-EV" },
        { "year": "2018", "product_code": "MJ118D-A" },
        { "year": "2018", "product_code": "MJ118D-W" },
        { "year": "2018", "product_code": "MM318D-A" },
        { "year": "2018", "product_code": "MM318D-L" },
        { "year": "2018", "product_code": "MM318D-W" },
        { "year": "2018", "product_code": "MM518D-L" },
        { "year": "2018", "product_code": "MM518D-L" },
        { "year": "2018", "product_code": "MM518D-W" },
        { "year": "2017", "product_code": "MJ117D-A" },
        { "year": "2017", "product_code": "MJ117D-W" },
        { "year": "2017", "product_code": "MM317D-A" },
        { "year": "2017", "product_code": "MM317D-W" },
        { "year": "2017", "product_code": "MM517D-L" },
        { "year": "2017", "product_code": "MM517D-L" },
        { "year": "2017", "product_code": "MM517D-W" },
        { "year": "2016", "product_code": "MJ116D-A" },
        { "year": "2016", "product_code": "MJ116D-W" },
        { "year": "2016", "product_code": "MJE16D-EV" },
        { "year": "2016", "product_code": "MM316D-A" },
        { "year": "2016", "product_code": "MM316D-W" },
        { "year": "2016", "product_code": "MM516D-L" },
        { "year": "2016", "product_code": "MM516D-L" },
        { "year": "2016", "product_code": "MM516D-W" },
        { "year": "2015", "product_code": "MC315D-A" },
        { "year": "2015", "product_code": "MC315D-W" },
        { "year": "2015", "product_code": "MM115D-A" },
        { "year": "2015", "product_code": "MM115D-W" },
        { "year": "2015", "product_code": "MM515D-L" },
        { "year": "2015", "product_code": "MME15D-EV" },
        { "year": "2015", "product_code": "MP315D-A" },
        { "year": "2015", "product_code": "MP315D-W" },
        { "year": "2014", "product_code": "MC314D-A" },
        { "year": "2014", "product_code": "MC314D-W" },
        { "year": "2014", "product_code": "MM114D-A" },
        { "year": "2014", "product_code": "MM114D-W" },
        { "year": "2014", "product_code": "MM514D-L" },
        { "year": "2014", "product_code": "MP314D-A" },
        { "year": "2014", "product_code": "MP314D-W" },
        { "year": "2013", "product_code": "MC313D-A" },
        { "year": "2013", "product_code": "MC313D-W" },
        { "year": "2013", "product_code": "MM113D-A" },
        { "year": "2013", "product_code": "MM113D-W" },
        { "year": "2013", "product_code": "MM513D-L" },
        { "year": "2013", "product_code": "MP313D-A" },
        { "year": "2013", "product_code": "MP313D-W" },
        { "year": "2012", "product_code": "HM512D-A" },
        { "year": "2012", "product_code": "HM512D-W" },
        { "year": "2012", "product_code": "MM112-A" },
        { "year": "2012", "product_code": "MM112-W" },
        { "year": "2012", "product_code": "MM312D-A" },
        { "year": "2012", "product_code": "MM312D-W" },
        { "year": "2011", "product_code": "HS511D-A" },
        { "year": "2011", "product_code": "HS511D-W" },
        { "year": "2011", "product_code": "MP111-A" },
        { "year": "2011", "product_code": "MP111-W" },
        { "year": "2011", "product_code": "MP311D-A" },
        { "year": "2011", "product_code": "MP311D-W" },
        { "year": "2010", "product_code": "HC510D-A" },
        { "year": "2010", "product_code": "HC510D-W" },
        { "year": "2010", "product_code": "HS310-A" },
        { "year": "2010", "product_code": "HS310D-A" },
        { "year": "2010", "product_code": "HS310D-W" },
        { "year": "2010", "product_code": "HS310-W" },
        { "year": "2010", "product_code": "MP310-A" },
        { "year": "2010", "product_code": "MP310-W" },
        { "year": "2010", "product_code": "MS110-A" },
        { "year": "2010", "product_code": "MS110-W" },
        { "year": "2009", "product_code": "HC309D-A" },
        { "year": "2009", "product_code": "HC309D-W" },
        { "year": "2009", "product_code": "HC509D-A" },
        { "year": "2009", "product_code": "HC509D-W" },
        { "year": "2009", "product_code": "HS309-A" },
        { "year": "2009", "product_code": "HS309-W" },
        { "year": "2009", "product_code": "HS709D-A" },
        { "year": "2009", "product_code": "HS709D-W" },
        { "year": "2009", "product_code": "MP309-A" },
        { "year": "2009", "product_code": "MP309-W" },
        { "year": "2009", "product_code": "MS109-A" },
        { "year": "2009", "product_code": "MS109-W" },
        { "year": "2009", "product_code": "MS309D-A" },
        { "year": "2009", "product_code": "MS309D-W" },
        { "year": "2008", "product_code": "HC308D-A" },
        { "year": "2008", "product_code": "HC308D-W" },
        { "year": "2008", "product_code": "HC508D-A" },
        { "year": "2008", "product_code": "HC508D-W" },
        { "year": "2008", "product_code": "HS708D-A" },
        { "year": "2008", "product_code": "HS708D-W" },
        { "year": "2008", "product_code": "MS108-A" },
        { "year": "2008", "product_code": "MS108-W" },
        { "year": "2008", "product_code": "MS308-A" },
        { "year": "2008", "product_code": "MS308-W" },
        { "year": "2007", "product_code": "HC307-A" },
        { "year": "2007", "product_code": "HS307D-A" },
        { "year": "2007", "product_code": "HS507-A" },
        { "year": "2007", "product_code": "HS707D-A" },
        { "year": "2007", "product_code": "MS107-A" },
        { "year": "2006", "product_code": "DM306-A" },
        { "year": "2005", "product_code": "DM305-A" },
        { "year": "2004", "product_code": "DM304-A" },
        { "year": "2003", "product_code": "MAX430VDN" },
        { "year": "2003", "product_code": "MAX730HDN" },
        { "year": "2003", "product_code": "MAX930HDN" }
    ],
    "ホンダ": [
        {"year": "2024", "product_code": "LX-240ZFE"},
        {"year": "2024", "product_code": "LXM-242ZFNi"},
        {"year": "2024", "product_code": "LXM-245ZFEi"},
        {"year": "2023", "product_code": "VX-240ZFE"},
        {"year": "2023", "product_code": "LXU-242NBi"},
        {"year": "2023", "product_code": "VXM-245ZFEi"},
        {"year": "2023", "product_code": "VXU-245VZi"},
        {"year": "2023", "product_code": "VXU-245FTi"},
        {"year": "2023", "product_code": "LXU-247NBi"},
        {"year": "2023", "product_code": "LXM-247VFLi"},
        {"year": "2023", "product_code": "LXM-247VFNi"},
        {"year": "2023", "product_code": "VXM-247VFNi"},
        {"year": "2023", "product_code": "VXM-247VFEi"},
        {"year": "2022", "product_code": "LXU-237NBi"},
        {"year": "2022", "product_code": "VXU-235VZi"},
        {"year": "2022", "product_code": "VXU-235FTi"},
        {"year": "2022", "product_code": "LXM-237VFLi"},
        {"year": "2022", "product_code": "LXM-237VFNi"},
        {"year": "2022", "product_code": "LXM-232VFEi"},
        {"year": "2022", "product_code": "VXM-237VFEi"},
        {"year": "2022", "product_code": "VXM-237VFNi"},
        {"year": "2022", "product_code": "VXM-235Ci"},
        {"year": "2022", "product_code": "VXM-234VFi"},
        {"year": "2022", "product_code": "VXM-227VFEi"},
        {"year": "2022", "product_code": "VXM-225VFEi"},
        {"year": "2022", "product_code": "VXU-225VZi"},
        {"year": "2022", "product_code": "VXU-225FTi"},
        {"year": "2021", "product_code": "VXM-227VFNi"},
        {"year": "2021", "product_code": "VXM-224VFi"},
        {"year": "2021", "product_code": "VXM-225Ci"},
        {"year": "2021", "product_code": "VXU-227DYi"},
        {"year": "2021", "product_code": "VXU-227SWi"},
        {"year": "2021", "product_code": "VXU-227NBi"},
        {"year": "2021", "product_code": "VXU-227SGi"},
        {"year": "2021", "product_code": "VRU-225Cvi"},
        {"year": "2021", "product_code": "VXM-215VFEi"},
        {"year": "2021", "product_code": "VXU-215VZi"},
        {"year": "2020", "product_code": "VXM-217VFNi"},
        {"year": "2020", "product_code": "VXM-217VFEi"},
        {"year": "2020", "product_code": "VXU-217DYi"},
        {"year": "2020", "product_code": "VXU-217SWi"},
        {"year": "2020", "product_code": "VXU-217NBi"},
        {"year": "2020", "product_code": "VXM-214VFi"},
        {"year": "2020", "product_code": "VXM-215Ci"},
        {"year": "2020", "product_code": "VXU-215FTi"},
        {"year": "2020", "product_code": "VXU-205FTi"},
        {"year": "2019", "product_code": "VXM-207VFNi"},
        {"year": "2019", "product_code": "VXM-207VFEi"},
        {"year": "2019", "product_code": "VXM-205VFEi"},
        {"year": "2019", "product_code": "VXM-204VFi"},
        {"year": "2019", "product_code": "VXU-207SWi"},
        {"year": "2019", "product_code": "VXU-207NBi"},
        {"year": "2018", "product_code": "VRM-195VFEi"},
        {"year": "2018", "product_code": "VRM-195VFi"},
        {"year": "2018", "product_code": "VXU-197SWi"},
        {"year": "2018", "product_code": "VXM-194VFi"},
        {"year": "2018", "product_code": "VXU-195NBi"},
        {"year": "2018", "product_code": "VXM-195VFEi"},
        {"year": "2018", "product_code": "VXM-195VFi"},
        {"year": "2018", "product_code": "VXM-197VFNi"},
        {"year": "2018", "product_code": "VXM-197VFEi"},
        {"year": "2017", "product_code": "VRM-185VFEi"},
        {"year": "2017", "product_code": "VXM-184VFi"},
        {"year": "2017", "product_code": "VXM-185VFEi"},
        {"year": "2017", "product_code": "VXM-185VFi"},
        {"year": "2017", "product_code": "VXM-185VFNi"},
        {"year": "2017", "product_code": "VXM-187VFEi"},
        {"year": "2017", "product_code": "VXM-187VFNi"},
        {"year": "2017", "product_code": "VXU-185NBi"},
        {"year": "2017", "product_code": "VXU-187SWi"},
        {"year": "2016", "product_code": "VRM-175VFEi"},
        {"year": "2016", "product_code": "VXM-174VFi"},
        {"year": "2016", "product_code": "VXM-174VFXi"},
        {"year": "2016", "product_code": "VXM-175VFi"},
        {"year": "2016", "product_code": "VXM-174CSi"},
        {"year": "2016", "product_code": "VXM-175VFEi"},
        {"year": "2016", "product_code": "VXM-175VFNi"},
        {"year": "2016", "product_code": "WX-171CP"},
        {"year": "2015", "product_code": "VRM-165VFEi"},
        {"year": "2015", "product_code": "VRM-165VFi"},
        {"year": "2015", "product_code": "VXM-164CSi"},
        {"year": "2015", "product_code": "VXM-164VFi"},
        {"year": "2015", "product_code": "VXM-164VFXi"},
        {"year": "2015", "product_code": "VXM-165VFi"},
        {"year": "2015", "product_code": "VXM-165VFEi"},
        {"year": "2015", "product_code": "VXM-165VFNi"},
        {"year": "2014", "product_code": "WX-151C"},
        {"year": "2014", "product_code": "WX-151CP"},
        {"year": "2014", "product_code": "VRM-155VFEi"},
        {"year": "2014", "product_code": "VRM-155VFi"},
        {"year": "2014", "product_code": "VXM-152VFi"},
        {"year": "2014", "product_code": "VXM-155C"},
        {"year": "2014", "product_code": "VXM-155VFEi"},
        {"year": "2014", "product_code": "VXM-155VFi"},
        {"year": "2014", "product_code": "VXM-155VFNi"},
        {"year": "2014", "product_code": "VXM-155VSi"},
        {"year": "2013", "product_code": "VXM-142VFi"},
        {"year": "2013", "product_code": "VXM-145C"},
        {"year": "2013", "product_code": "VXM-145VFEi"},
        {"year": "2013", "product_code": "VXM-145VFi"},
        {"year": "2013", "product_code": "VXM-145VFNi"},
        {"year": "2013", "product_code": "VXM-145VSi"},
        {"year": "2012", "product_code": "VXM-135VFN"},
        {"year": "2012", "product_code": "VXM-135VFNi"},
        {"year": "2012", "product_code": "WX-135CP"},
        {"year": "2011", "product_code": "VXH-128VF"},
        {"year": "2011", "product_code": "VXM-122VF"},
        {"year": "2011", "product_code": "VXM-122VFi"},
        {"year": "2011", "product_code": "VXM-128C"},
        {"year": "2011", "product_code": "VXM-128VS"},
        {"year": "2011", "product_code": "VXM-128VSX"},
        {"year": "2011", "product_code": "VXM-128VSXi"},
        {"year": "2010", "product_code": "VXH-112VS"},
        {"year": "2010", "product_code": "VXM-118C"},
        {"year": "2010", "product_code": "VXM-118VS"},
        {"year": "2009", "product_code": "VXH-108VF"},
        {"year": "2009", "product_code": "VXH-108VFi"},
        {"year": "2009", "product_code": "VXM-105CF"},
        {"year": "2009", "product_code": "VXM-108CS"},
        {"year": "2009", "product_code": "VXS-102VFi"},
        {"year": "2009", "product_code": "VXS-102VSi"},
        {"year": "2008", "product_code": "VXH-092CV"},
        {"year": "2008", "product_code": "VXH-093CVi"},
        {"year": "2008", "product_code": "VXH-098CV"},
        {"year": "2008", "product_code": "VXH-098CVU"},
        {"year": "2008", "product_code": "VXM-090"},
        {"year": "2008", "product_code": "VXM-090CV"},
        {"year": "2008", "product_code": "VXM-095C"},
        {"year": "2008", "product_code": "VXS-092CVi"},
        {"year": "2007", "product_code": "VXD-085C"},
        {"year": "2007", "product_code": "VXD-085CV"},
        {"year": "2007", "product_code": "VXH-082C"},
        {"year": "2007", "product_code": "VXH-082MCV"},
        {"year": "2007", "product_code": "VXH-083CVi"},
        {"year": "2007", "product_code": "VXH-088CV"},
        {"year": "2007", "product_code": "VXH-089CV"},
        {"year": "2007", "product_code": "VXH-089CVduo"},
        {"year": "2007", "product_code": "VXM-085C"},
        {"year": "2006", "product_code": "VXD-074C"},
        {"year": "2006", "product_code": "VXD-074CV"},
        {"year": "2006", "product_code": "VXD-075C"},
        {"year": "2006", "product_code": "VXD-079C"},
        {"year": "2006", "product_code": "VXD-079MCV"},
        {"year": "2006", "product_code": "VXH-071MCV"},
        {"year": "2006", "product_code": "VXH-071MCVi"},
        {"year": "2006", "product_code": "VXH-072C"},
        {"year": "2006", "product_code": "VXH-072CV"},
        {"year": "2006", "product_code": "VXH-079CV"},
        {"year": "2005", "product_code": "VXD-069MCV"},
        {"year": "2005", "product_code": "VXH-061MCV"},
        {"year": "2005", "product_code": "VXH-061MCVi"},
        {"year": "2005", "product_code": "VXH-062C"},
        {"year": "2005", "product_code": "VXH-062CV"},
        {"year": "2005", "product_code": "VXH-069CV"},
        {"year": "2004", "product_code": "VXD-055C"},
        {"year": "2004", "product_code": "VXD-059CE"},
        {"year": "2004", "product_code": "VXD-059CV"},
        {"year": "2004", "product_code": "VXD-059MC"},
        {"year": "2004", "product_code": "VXH-051MCV"},
        {"year": "2004", "product_code": "VXH-051MCVi"},
        {"year": "2004", "product_code": "VXH-052C"},
        {"year": "2004", "product_code": "VXH-052CV"},
        {"year": "2004", "product_code": "VXH-059CV"},
        {"year": "2003", "product_code": "VXD-045MC"},
        {"year": "2003", "product_code": "VXH-042C"},
        {"year": "2003", "product_code": "VXH-049C"},
        {"year": "2003", "product_code": "VXD-049C"},
        {"year": "2003", "product_code": "VXD-049MC"},
        {"year": "2002", "product_code": "VXD-039MC"},
        {"year": "2002", "product_code": "VXD-032Ci"},
        {"year": "2002", "product_code": "VXD-032Mi"},
        {"year": "2001", "product_code": "VXD-022Mi"}
    ],
    "ミツビシ": [
        { "year": "2023", "product_code": "MM223D-LM" },
        { "year": "2023", "product_code": "DA22JM" },
        { "year": "2022", "product_code": "MM222D-LM" },
        { "year": "2021", "product_code": "デリカ D:5" },
        { "year": "2020", "product_code": "MJ120D-WM" },
        { "year": "2020", "product_code": "MJ320D-WM" },
        { "year": "2020", "product_code": "MM320D-LM" },
        { "year": "2020", "product_code": "デリカ D:5ナビ" },
        { "year": "2019", "product_code": "MM319D-LM" },
        { "year": "2019", "product_code": "MM319D-WM" },
        { "year": "2019", "product_code": "デリカ D:5ナビ" },
        { "year": "2018", "product_code": "MJ118D-W" },
        { "year": "2018", "product_code": "MM318D-LM" },
        { "year": "2018", "product_code": "MM318D-WM" },
        { "year": "2017", "product_code": "MJ117D-WM" },
        { "year": "2017", "product_code": "MM317D-WM" },
        { "year": "2016", "product_code": "MJ116D-WM" },
        { "year": "2016", "product_code": "MM316D-WM" }
    ],
    "スバル": [
        { "year": "2023", "product_code": "H0014SJ040SS" },
        { "year": "2012", "product_code": "H0018AJ003GG" },
        { "year": "2011", "product_code": "GCX711W" },
        { "year": "2010", "product_code": "GCX710W" },
        { "year": "2009", "product_code": "GCX809" },
        { "year": "2008", "product_code": "GCX308" },
        { "year": "2008", "product_code": "GCX708A" },
        { "year": "2008", "product_code": "GCX708AW" }
    ],
    "スズキ": [
        {"year": "2025", "product_code": "99090-69U25-P01"},
        {"year": "2025", "product_code": "99098-69U25-P02"},
        {"year": "2025", "product_code": "99098-69U35-P03"},
        {"year": "2025", "product_code": "99097-80T35-P04"},
        {"year": "2025", "product_code": "99098-69U45-K01"},
        {"year": "2025", "product_code": "99097-80T45-K02"},
        {"year": "2025", "product_code": "99097-80T55-K03"},
        {"year": "2024", "product_code": "99099-77R23-N01"},
        {"year": "2024", "product_code": "99090-53U24-P11"},
        {"year": "2024", "product_code": "99098-53U24-P12"},
        {"year": "2024", "product_code": "99097-69T24-P13"},
        {"year": "2024", "product_code": "99098-53U34-P14"},
        {"year": "2024", "product_code": "99097-69T34-P15"},
        {"year": "2024", "product_code": "99098-53U44-K11"},
        {"year": "2024", "product_code": "99097-69T44-K12"},
        {"year": "2023", "product_code": "99090-53U23-P01"},
        {"year": "2023", "product_code": "99098-53U23-P02"},
        {"year": "2023", "product_code": "99097-69T23-P03"},
        {"year": "2023", "product_code": "99098-53U33-P04"},
        {"year": "2023", "product_code": "99097-69T33-P05"},
        {"year": "2023", "product_code": "99098-53U43-K01"},
        {"year": "2023", "product_code": "99097-69T43-K02"},
        {"year": "2022", "product_code": "99090-83S22-P01"},
        {"year": "2022", "product_code": "99098-83S32"},
        {"year": "2022", "product_code": "99097-79R22-P03"},
        {"year": "2022", "product_code": "99097-79R32"},
        {"year": "2020", "product_code": "99000-79CD0"},
        {"year": "2022", "product_code": "99097-79R42-K02"},
        {"year": "2021", "product_code": "99000-79CG5-W00"},
        {"year": "2021", "product_code": "99000-79CH5-W00"},
        {"year": "2021", "product_code": "99000-79CG0"},
        {"year": "2021", "product_code": "99000-79CH0"},
        {"year": "2021", "product_code": "99000-79CF0"},
        {"year": "2021", "product_code": "99000-79CJ5-W00"},
        {"year": "2021", "product_code": "99000-79CJ5-WL0"},
        {"year": "2021", "product_code": "99000-79CJ0"},
        {"year": "2020", "product_code": "99000-79CA0"},
        {"year": "2020", "product_code": "99000-79CB0"},
        {"year": "2020", "product_code": "99000-79CB1-W00"},
        {"year": "2020", "product_code": "99000-79CB5"},
        {"year": "2020", "product_code": "99000-79CB6-W00"},
        {"year": "2020", "product_code": "99000-79CC0"},
        {"year": "2020", "product_code": "99000-79CC1"},
        {"year": "2020", "product_code": "99000-79CC1-W00"},
        {"year": "2020", "product_code": "99000-79CD1-W00"},
        {"year": "2013", "product_code": "GCX513"},
        {"year": "2013", "product_code": "GCX613"},
        {"year": "2013", "product_code": "GCX613W"},
        {"year": "2013", "product_code": "MDV-L300"},
        {"year": "2013", "product_code": "MDV-X500"},
        {"year": "2012", "product_code": "CQ-UZ02J0CJ"},
        {"year": "2012", "product_code": "CQ-XZ02J0CJ"},
        {"year": "2012", "product_code": "GCX612"},
        {"year": "2012", "product_code": "GCX712"},
        {"year": "2011", "product_code": "GCX111"},
        {"year": "2011", "product_code": "GCX311"},
        {"year": "2011", "product_code": "GCX711"},
        {"year": "2011", "product_code": "NVA-MS3111"},
        {"year": "2011", "product_code": "NVA-MS3311"},
        {"year": "2011", "product_code": "NVA-MS3511"},
        {"year": "2010", "product_code": "GCX710"},
        {"year": "2010", "product_code": "GCX810"},
        {"year": "2010", "product_code": "NVA-HD3710"},
        {"year": "2010", "product_code": "NVA-HD3810"},
        {"year": "2010", "product_code": "NVA-MS3110"},
        {"year": "2010", "product_code": "NVA-MS3310"},
        {"year": "2009", "product_code": "AVIC-MRZ3147ZS"},
        {"year": "2009", "product_code": "GCX209"},
        {"year": "2009", "product_code": "GCX809"},
        {"year": "2009", "product_code": "NVA-HD3609"},
        {"year": "2009", "product_code": "NVA-HD3809"},
        {"year": "2009", "product_code": "NVA-MS3109"},
        {"year": "2009", "product_code": "NVA-MS3309"},
        {"year": "2008", "product_code": "GCX208"},
        {"year": "2008", "product_code": "GCX308"},
        {"year": "2008", "product_code": "GCX708A"},
        {"year": "2008", "product_code": "GCX808"},
        {"year": "2008", "product_code": "NVA-HD3680"},
        {"year": "2008", "product_code": "NVA-HD3780"},
        {"year": "2008", "product_code": "NVA-HD3880"},
        {"year": "2008", "product_code": "NVA-MS3180"},
        {"year": "2008", "product_code": "NVA-MS3280"},
        {"year": "2007", "product_code": "NVA-HD3770"}
    ],
    "ダイハツ": [
        { "year": "2011", "product_code": "NMZP-W61" },
        { "year": "2025", "product_code": "NMBN-Z75DS" },
        { "year": "2025", "product_code": "NMZK-W75D" },
        { "year": "2025", "product_code": "NMZK-W75DE" },
        { "year": "2023", "product_code": "NMZL-Y73D" },
        { "year": "2023", "product_code": "NMZN-Y73D" },
        { "year": "2008", "product_code": "NMCC-D58" },
        { "year": "2023", "product_code": "NMZL-W73D" },
        { "year": "2023", "product_code": "NMZN-W73D" },
        { "year": "2023", "product_code": "NMZK-W73D" },
        { "year": "2023", "product_code": "NMZN-Z73DS" },
        { "year": "2022", "product_code": "NMZN-Z72DS" },
        { "year": "2022", "product_code": "NMZN-Y72DS" },
        { "year": "2022", "product_code": "NMZN-Y72D" },
        { "year": "2022", "product_code": "NSZN-X72D" },
        { "year": "2022", "product_code": "NMZN-W72D" },
        { "year": "2022", "product_code": "NMZL-Y72D" },
        { "year": "2022", "product_code": "NMZL-W72D" },
        { "year": "2022", "product_code": "NMZK-W72D" },
        { "year": "2021", "product_code": "NSZN-Y71DS" }
    ],
    "マツダ": [
        { "year": "2013", "product_code": "A9CF V6 650" },
        { "year": "2013", "product_code": "C9CF V6 650" },
        { "year": "2012", "product_code": "C9NC V6 650" },
        { "year": "2012", "product_code": "C9P8 V6 650" },
        { "year": "2012", "product_code": "Z9C9 V6 650" },
        { "year": "2011", "product_code": "C9P7 V6 650" },
        { "year": "2011", "product_code": "C9Y8 V6 650" },
        { "year": "2010", "product_code": "C9CE V6 650" },
        { "year": "2010", "product_code": "C9P6 V6 650" },
        { "year": "2010", "product_code": "C9TA V6 650" },
        { "year": "2010", "product_code": "C9Y7 V6 650" },
        { "year": "2009", "product_code": "C9CD V6 650B" },
        { "year": "2009", "product_code": "C9P5 V6 650" },
        { "year": "2009", "product_code": "C9T9 V6 650" },
        { "year": "2009", "product_code": "C9Y6 V6 650" },
        { "year": "2008", "product_code": "C9CD V6 650" },
        { "year": "2008", "product_code": "C9CD V6 650A" },
        { "year": "2008", "product_code": "C9Y4 V6 650" },
        { "year": "2008", "product_code": "NCCD V6 650" },
        { "year": "2007", "product_code": "C9CB V6 650" },
        { "year": "2007", "product_code": "C9CC V6 650" },
        { "year": "2007", "product_code": "C9P3 V6 650" },
        { "year": "2007", "product_code": "C9Y2 V6 650" },
        { "year": "2007", "product_code": "C9Y3 V6 650" },
        { "year": "2007", "product_code": "NCP3 V6 650" }
    ]
}

export const BASIC_YEARS = [
    '2025(R07)', '2024(R06)', '2023(R05)', '2022(R04)', '2021(R03)', '2020(R02)',
    '2019(H31/R01)',
    '2018(H30)', '2017(H29)', '2016(H28)', '2015(H27)', '2014(H26)', '2013(H25)',
    '2012(H24)', '2011(H23)', '2010(H22)', '2009(H21)', '2008(H20)', '2007(H19)',
    '2006(H18)', '2005(H17)', '2004(H16)', '2003(H15)', '2002(H14)', '2001(H13)',
    '2000(H12)', '1999(H11)'
];

export const CAR_YEARS = [
    "R7 / 2025", "R6 / 2024", "R5 / 2023", "R4 / 2022", "R3 / 2021", "R2 / 2020",
    "R1 / 2019", "H31 / 2019",
    "H30 / 2018", "H29 / 2017", "H28 / 2016", "H27 / 2015", "H26 / 2014",
    "H25 / 2013", "H24 / 2012", "H23 / 2011", "H22 / 2010", "H21 / 2009",
    "H20 / 2008", "H19 / 2007", "H18 / 2006", "H17 / 2005", "H16 / 2004",
    "H15 / 2003", "H14 / 2002", "H13 / 2001", "H12 / 2000"
];

// 月の固定データ
export const MONTHS = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'];

export const TVING_NOTES_DATA = {
    "common": [
        "車両メーカーの仕様変更等により正常に作動しなくなる場合があります。",
        "「Apple CarPlay」「Android Auto」等、アプリの作動は未確認です。",
        "サービスホールスイッチタイプの適合が記載されている場合は、車両にサービスホールの空きやサイズをご確認ください。サービスホールの空やサイズが異なる場合にはお取り付けできません。"
    ],
    "1": "フリーテレビングでナビゲーション操作が可能になります。",
    "2": "パーキングブレーキアラーム機能により、TV画面に「パーキングブレーキをご確認下さい」と表示される場合がありますので、ナビゲーション本体の設定でこの機能を停止して下さい。",
    "3": "TV視聴には「TV」オプションサービスが必要な場合があります。",
    "4": "DVD視聴には「CD・DVDデッキ」のオプションが必要な場合があります。",
    "5": "ハイブリッド車は「エコ情報」画面でタイヤが回転しなくなる場合があります。",
    "6": "走行中、画面表示がナビゲーションの場合、車両側TVボタンを押すだけではTV画面に切り替わらない時があります。この場合は車両ステアリングスイッチのモードボタンでTVをご選択すると走行中のTVが視聴可能です。",
    "7": "本製品作動中、ナビゲーションの自車位置が不正確になります。自車位置情報を必要とする機能をご使用の際は本製品を【ノーマルモード】にして自車位置が正確な状態で使用してください。。",
    "8": "本製品作動中、ナビゲーションの自車位置表示は弊社独自の方法で動き、おおよその自車位置を表示します。使用状況や周辺の環境により誤差が生じる場合があります。ナビ自車位置情報に基づく機能は画面に表示している自車位置に基づき作動します。より正確な自車位置情報を必要とする機能をご使用の際は本製品を【ノーマルモード】にして自車位置が正確な状態で使用してください。",
    "9": "車両ナビゲーションの仕様により、本製品作動中、GPSが受信できない状況（トンネル内 等）では自車位置が停止する場合があります。",
    "10": "「レーンチェンジアシスト（LCA）付車」「レーンチェンジアシスト（LCA）無車」をご確認ください。【LCA付車】には【 MS-235/235C/ST-235 】【 CTN-107AS/107ASC/107AST 】を取り付けないでください。誤って取り付けされた場合、「レーンチェンジアシスト（LCA）」などの機能が停止し、メーター内にメッセージが表示されます。レーンチェンジアシスト（LCA）の有無は、マルチインフォメーションディスプレイの「車両設定」メニューから「LCA」表示の有無をご確認ください。",
    "11": "切替スイッチのLEDは車両ECUの起動中は点灯し、ECUスリープモードに移行すると消灯します。車両ECUの状態により点灯又は消灯しますが異常ではありません。",
    "12": "車両のサービスホールに空きスペースがない為「サービスホールスイッチタイプ」の取り付けはできません。",
    "13": "リアエンブレムが【HYBRID SYNERGY DRIVE】の場合は一部改良前車両です。（MS-235/MS-235C/ST-235/CTN-107AS/CTN-107ASC/CTN-107ASTが適合）　リアエンブレムが【●HEV】の場合は一部改良後車両です。（CTN-111AS/CTN-111ASC/CTN-111ASTが適合）",
    "14": "メーカー純正TVチューナーの設定がないため、車両にTV機能がありません。",
    "15": "本製品作動中、はナビゲーション操作も可能となりますが、地図画面は表示されたまま自車位置が不正確になります。その際、車速信号及び自車位置に付随する機能は使用出来なくなりますが故障ではありません。（ エネルギーモニター画面での走行中タイヤ回転・自車位置表示・ルート案内・到着予想時刻・残距離表示等）",
    "16": "サービスホールスイッチタイプの場合は、車種毎にパネルのサイズが異なりますので、装着予定車両のパネルサイズと「パネル埋め込みスイッチサイズ確認（PDF）」でサイズをご確認の上お買い求めください。",
    "17": "ナビゲーションの機能により画面に「車速信号が検出できません。車速信号コードの接続をご確認ください。」の文字が表示される場合がありますが、LED消灯（ノーマル状態）にしていただくと表示されません。",
    "18": "パーキングブレーキ操作を行った際、一瞬TV画面が黒くなる場合がありますが異常ではありません。",
    "19": "エネルギーモニターの画面で走行中タイヤが回転しなくなりますが、故障ではありません。",
    "20": "燃費計算ができなくなりますのでご注意下さい。",
    "21": "ディスプレイオーディオにナビゲーション機能がありません。",
    "22": "テレビ視聴中は燃費計算に誤差が生じます。",
    "23": "スイッチ点灯中（テレビ視聴モード）は、自車位置が不正確になります。",
    "24": "緑LED（テレビ視聴モード）のままナビゲーション操作も可能です。",
    "25": "取り付け場所は上部モニター裏となります。",
    "26": "TV視聴/ナビ操作はスイッチ切り替えタイプになりますので、TV視聴モード中及びナビゲーション操作モード中は自車位置が不正確に（停止）になる為、「プロパイロット2.0」「プロパイロット（ナビリンク機能付き）」「ナビ協調機能」「EVメニュー」などは使用できなくなるまたは、使用に制限がかかりますので、必ず橙LED（ノーマルモード）でご使用ください。",
    "27": "TV視聴/ナビ操作はスイッチ切り替えタイプになりますので、TV視聴モード中及びナビゲーション操作モード中は自車位置が不正確になります。テレビ視聴モード中はナビゲーションの自車位置が不正確になる為、地図情報に基づく機能などは使用できません",
    "28": "R1/8以前の登録車両であっても「NISSAN」エンブレム装着車は【CTN-202】が適合になります。",
    "29": "クリッパー/クリッパーリオ/アトラスについては適合対象外となりますのでご注意下さい。",
    "30": "パーキングブレーキアラーム機能が作動する場合は、ナビゲーション本体の設定でこの機能を停止して下さい。",
    "31": "テレビが映る状態では下記の機能・項目が使用できなくなります。<機能>ノーズビューカメラ、リアビューカメラ＜項目＞走行情報、環境情報、メンテナンス、アクセサリー等",
    "32": "ekシリーズ/デリカミニ以外は適合対象外となりますのでご注意下さい。",
    "33": "緑LED（テレビ視聴モード）のままナビゲーション操作も可能です。TV視聴/ナビ操作はスイッチ切り替えタイプになりますので、TV視聴モード中及びナビゲーション操作モード中は自車位置が不正確になります。TV視聴モード中、ナビゲーションの自車位置が不正確になる為、「マイパイロット内のナビリンク機能」等、地図情報に基づく機能などは使用できなくなります。",
    "34": "R7/2～はパネルの一部がネジ止めになっていますので脱着の際はご注意ください。",
    "35": "デリカ D:5　ナビゲーションの脱着作業において、シフトノブの取り外しが必要になりますが、シフトノブ固定用ネジは再使用できませんので必ず新品をご用意ください。（純正部品番号　2400A596）",
    "36": "「CTN-303」は、「TV視聴：オート/ナビ操作：切替タイプ」です。緑LED（テレビ視聴モード）ではナビゲーション操作は出来ませんので、スイッチを操作し、赤LED（ナビゲーション操作モード）でナビゲーション操作を行ってください。",
    "37": "「CTN-304/CTN-305」は、緑LED（テレビ視聴モード）のままナビゲーション操作も可能です。",
    "38": "パーキングブレーキ操作を行った際、一瞬TV画面にメッセージが表示される場合がありますが、異常ではありません。",
    "39": "「CTN-301」は、マルチビューカメラ装着車の場合、カメラ自動表示機能（車両機能）により車速等でカメラ画面に切り替わります。切り替わる前の表示にしたい場合は画面スイッチ（アイコン）等で切り替えて下さい。",
    "40": "「CTN-302」はカメラ自動表示機能によるカメラ画面は製品により制御され切り替わらず、ナビゲーション画面等が継続表示します。",
    "41": "対応する一部車両で画面が暗くなる症状がありますが、個々の車両の特性によるもので異常ではありません。[対策]・・・黒画面が表示された場合は車両側のナビのスイッチを押した後、テレビのスイッチを再度押すことでテレビ画面が表示されます。",
    "42": "マルチビューカメラ制御機能無：マルチビューカメラ付車の場合、カメラ自動表示機能により車速等でカメラ画面に切り替わります。",
    "43": "マルチビューカメラ制御機能有：ナビモード中、カメラ自動表示機能によるカメラ画面は製品により制御され切り換わらず、ナビゲーション画面等が継続表示します。（テレビ視聴モード中は制御されません。",
    "44": "「CTN-〇〇〇」は「TV視聴：オート/ナビ操作：切替タイプ」です。緑LED（テレビ視聴モード）ではナビゲーション操作は出来ませんので、スイッチを操作し、赤LED（ナビゲーション操作モード）でナビゲーション操作を行ってください。「CTN-〇〇〇S」は「TV視聴：切替/ナビ操作：切替タイプ」です。橙LED（ノーマルモード）ではテレビ視聴及びナビゲーション操作はできませんので、スイッチを操作し、緑LED（テレビ視聴モード）、赤LED（ナビゲーション操作モード）に切り替えてご使用ください。",
    "45": "「CTN-309/CTN-309S」は、本製品のスイッチ操作を行った際、一瞬TV画面にメッセージが表示される場合がありますが異常ではありません。",
    "46": "ステップワゴンに装着する場合、ナビゲーション脱着作業において、フロントピラーガーニッシュの取り外しが必要ですが、ピラーガーニッシュ固定のクリップは再使用できませんので新品クリップをご用意ください。（ホンダ純正番号：91561-T20-A01）",
    "47": "テレビ機能、ナビゲーション機能はありません。外部入力（HDMI）映像を走行中に視聴するための【フリーテレビング】適合となります。",
    "48": "緑LED（テレビ視聴モード）のままナビゲーション操作も可能です。本製品をご使用中は、i-DM エンディング表示のスコア評価とアドバイスが機能しなくなります。（i-DMについての詳細は車両取扱説明書をご参照ください）",
    "49": "TV視聴/ナビ操作はスイッチ切り替えタイプになりますので、TV視聴モード中及びナビゲーション操作モード中は自車位置が不正確になります。",
    "50": "「CX-3」は、H27/3～マツダコネクト7インチセンターディスプレイ装着車 / R3/10～マツダコネクト8インチセンターディスプレイ装着車",
    "51": "車両仕様により本製品作動中、トンネル 等で　メーターに「交通標識認識システム性能が低下しています。ナビゲーションとの連携が出来ません」 「SDカードを確認してください」　と交互に表示される場合があります。本製品をOFF または トンネル通過後しばらく走行すると表示が消えます。",
    "52": "R1/9～R3/9マツダコネクト7インチセンターディスプレイ装着車 / R3/10～マツダコネクト8インチセンターディスプレイ装着車",
    "53": "ディスプレイオーディオ装着車は、テレビチューナー非搭載のため、テレビの視聴はできません。",
    "54": "R7/2～はパネルの一部がネジ止めになっていますので脱着の際はご注意ください。",
    "55": "テレビ視聴にはディーラーオプションの「ＴＶアンテナセット」が必要です。",
    "56": "",
    "57": "",
    "58": "",
    "59": "「BTN-T10」はLEDスイッチ、「BTN-T10A」「BTN-T10C」はサービスホールスイッチです。",
    "60": "「BTN-S31」はLEDスイッチ、「BTN-S31C」はサービスホールスイッチです。",
    "61": "「CTN-307」は「TV視聴：オート/ナビ操作：切替タイプ」です。「CTN-307S」は「TV視聴：切替/ナビ操作：切替タイプ」です。",
    "62": "「CTN-308」は「TV視聴：オート/ナビ操作：切替タイプ」です。「CTN-308S」は「TV視聴：切替/ナビ操作：切替タイプ」です。",
    "63": "「CTN-309」は「TV視聴：オート/ナビ操作：切替タイプ」です。「CTN-309S」は「TV視聴：切替/ナビ操作：切替タイプ」です。",
    "64": "ディスプレイオーディオにTV機能がありません。走行中のUSBの動画再生が可能になります。",
    "65": "【車速センサーが接続されていません。】と表示されますが、異常ではなく、暫くすると表示は消えます。",
    "66": "標準装備のVTR/ipod入力の動画/音楽再生が走行中も可能になります。各種アプリの動作保証は致しかねます。",
    "67": "アルティスについては、適合対象外です。",
    "901": "アルト・スペーシア・スペーシアベース・ソリオ・ハスラー・ラパン・ワゴンRスマイル 以外の車両",
    "902": "全方位モニター非装着車 【アルト（HA97S R4/1～）】【スペーシア（MK53S R4/1～R5/11）（MK54S 94S R5/12～）】【スペーシアベース（MK33V R4/8～）】【ソリオ（MA27S 37S R2/12～R7/1）（MAD7S R7/2～）】【ハスラー（MR52S 92S R2/2～）】【ラパン（HE33S R4/7～）】【ワゴンRスマイル（MX81S 91S R3/9～）】",
    "903": "全方位モニター装着車 【アルト（HA97S R4/1～）】【スペーシア（MK53S R4/1～R5/11）】【スペーシアベース（MK33V R4/8～）】【ソリオ（MA37S R2/12～R7/1）】【ハスラー（MR52S 92S R2/2～R4/5）】【ラパン（HE33S R4/7～）】【ワゴンRスマイル（MX91S R3/9～）】",

};

export const MAGICONE_NOTES_DATA = {
    "1": "ナビゲーションのバックカメラ入力に接続すると「R」レンジ時は「後方映像」を表示し、「R」レンジ時以外でも「前方映像」の表示が可能になります。",
    "2": "車両によりミラー裏コネクターに化粧カバーが取り付けられている場合がありますが、本製品取り付け時、化粧カバーが使用できなくなる場合があります。",
    "3": "車両によってはナビゲーションに映写されるバック映像にちらつきなどが生じる場合がありますが車両特性によるものでAV-C63の異常ではありません。",
    "4": "デジタルインナーミラー全面に映写されるバック映像とナビゲーションに映写されるバック映像では映し出される範囲が異なりますが異常ではありません。",
    "5": "記載全ての型式で作動確認はできておりません。特殊架装車など、車両仕様によってはAV-C63が装着できない場合があります。",
    "6": "本製品を装着することで自動防眩インナーミラーのバックモニター映像にノイズが見える場合があります。バックモニター映像にノイズが発生している場合は、ナビゲーションに映写した場合にもノイズが見える場合があります。接続するナビゲーションの画面比率によっては、画面の端に帯が入る場合がありますが異常ではありません。",
    "7": "市販デジタルインナーミラーにバックカメラ映像は映りません。また、市販ナビゲーションにRCAのバックカメラ入力がない場合は装着できません。",
    "8": "本製品を装着することでデジタルインナーミラーのバックモニター映像にノイズが見える場合があります。\nバックモニター映像にノイズが発生している場合は、ナビゲーションに映写した場合にもノイズが見える場合があります。\n接続するナビゲーションの画面比率によっては、画面の端に帯が入る場合がありますが異常ではありません。",
    "9": "純正自動防眩インナーミラー（バックモニター内臓）と市販デジタルインナーミラーの併用はできません。",
    "10": "「視界補助パック」付車であっても『デジタルミラーモード』でスマートインナーミラー内に「バックカメラ映像」が表示されない車両は【AV-C48】が適合になります。",
    "11": "スマートインナーミラー内のカメラ映像も同時に表示します。",
    "12": "スマートインナーミラー内のカメラ映像は表示しなくなります。",
    "13": "「マルチビューバックガイドモニターカメラ」「雨滴除去機能付きマルチビューバックガイドモニターカメラ」は適合しません。またカメラのコネクタ形状は一般的な純正カメラと同じです。形状では判別することができないため、必ずディーラー様などの車両販売店でご確認ください。",
    "14": "「雨滴除去機能付きバックカメラ」は動作未確認です。またカメラのコネクタ形状は一般的な純正カメラと同じです。形状では判別することができないため、必ずディーラー様などの車両販売店でご確認ください。",
    "15": "カメラ起動のタイミングにより正常に映写できない場合があります。（ただし、マジコネ「AV-C02」と弊社カメラ製品（AV-FBC01R・AV-FBC02R・AV-FBC03R）の電源をACC接続としてご使用いただく場合のみ使用可能です。）",
    "16": "「AV-C13」は、ナビゲーションのバックカメラ入力に接続すると「R」レンジ時は「後方映像」を表示します。（ご注意：「R」レンジ以外では表示しません。）",
    "17": "「AV-C13FA」は、ナビゲーションのバックカメラ入力に接続すると「R」レンジ時は「後方映像」を表示し、「R」レンジ時以外でも「前方映像」を表示が可能になります。",
    "18": "日産ディーラーオプションナビゲーションに純正カメラ映像を映し出す場合は【マジコネ ニッサン ディーラーオプション適合表】に記載の≪マジコネ バックカメラ“接続ハーネス”≫と併用することで可能になります。",
    "19": "ナビゲーションのバックカメラ入力に接続すると「R」レンジ時は「後方映像」を表示します。（ご注意：「R」レンジ以外では表示しません。）",
    "20": "適合するナビゲーションはマジコネ ディーラーオプション適合 内 「AV-C55」適合機種に限ります。",
    "21": "「AV-C13FC/AV-C13FD」は、ナビゲーションのバックカメラ入力に接続すると「R」レンジ時は「後方映像」を表示し、「R」レンジ時以外でも「前方映像」を表示が可能になります。",
    "22": "カメラスイッチを押し、メーター内にアラウンドビューモニター映像が表示している事を確認してください。アラウンドビューモニター映像が表示していない場合やディーラーオプションナビのみに表示していた場合は、ディーラーにて「CONSULT」による設定変更が必要になります。（作業工賃についてはディーラーへご確認ください。）",
    "23": "カメラ視点固定式：「AV-C05」 / カメラ視点切替式：「AV-C06」のどちらかをご選択下さい。",
    "24": "カメラ視点固定式：「AV-C61」 / カメラ視点切替式：「AV-C62」のどちらかをご選択下さい。",
    "25": "○一部車両で画面下部の映像が乱れて表示されますが、カメラの仕様によるものです。市販ナビゲーション等にマジコネを用いてカメラ映像を表示すると、カメラ映像が暗い、変色する、映らない、といった症状が発生する場合があります。この場合にはマジコネ映像増幅器【AV-AMP01 (1,980 円 税込）】を取り付けて頂く事で症状が改善されます。",
    "26": "三菱純正スマートフォン連携ディスプレイオーディオ（SDA）から市販ナビゲーションへ載せ替えた後も、マルチアラウンドモニター（バードアイビュー機能付）映像をナビゲーション画面に表示させる事ができます。スマートフォン連携ディスプレイオーディオ（SDA）を取り外すことにより、下記の連携する機能は使用できなくなります。\n◆スマートフォン連携ディスプレイオーディオ（SDA）連携ETC/ETC2.0 ◆スマートフォン連携ディスプレイオーディオ（SDA)での車両機能設定\n◆タッチパッドコントローラー ◆リンクシステム ◆ボイスコマンド機能 ◆ステアリングスイッチによる表示「ビュー」の変更 など",
    "27": "カメラコントローラーキット（純正品番/MZ598427）が必要になります。",
    "28": "6.2インチディスプレイオーディオを取り外し、市販ナビゲーションに載せ替え用。スマートパノラマパーキングアシスト機能は使用できなくなります。\n市販ナビゲーションのバックカメラ入力に接続すると「R」レンジ時は「後方映像」を表示し、「R」レンジ時以外でも「前方映像」の表示が可能になります。",
    "29": "カメラコントローラーキット（マツダ品番 ： Z9N1 V6 55Y）が必要になります。",
    "30": "左右確認サポート作動中の通知音はなりません（マーカー表示のみ）",
    "31": "スバルディーラーオプション「用品接続ボックス」が装着されている車両には「AV-C39」は使用しません。「AV-C39」を使用してスバルディーラーオプションリアビューカメラを接続した場合、ガイドライン・ステアリング連動ガイドの表示は行いません。また「用品接続ボックス」を使用するその他ディーラーオプションの装着はできません。",
    "32": "「AV-C35」は、ナビゲーションのバックカメラ入力に接続すると「R」レンジ時は「後方映像」を表示します。（ご注意：「R」レンジ以外では表示しません。）",
    "33": "「AV-C35F」は、ナビゲーションのバックカメラ入力に接続すると「R」レンジ時は「後方映像」を表示し、「R」レンジ時以外でも「前方映像」を表示が可能になります。",
    "34": "【後退時左右確認サポート機能】および【自動俯瞰（ふかん）機能】は使用出来ません。ガイドラインは固定表示となり非表示にする事は出来ません。",
    "35": "カメラコントローラーキット（CA7V：純正品番/99000-79CA1）が必要になります。",
    "36": "トランスミッションが「5AGS」の車両には取り付けできません。",
    "37": "【5極コネクター仕様車】と【RCAピンプラグ仕様車】が混在している可能性がありますので、必ず実車をご確認ください。",
    "38": "カメラ視点の切り替えはできません。",
    "39": "カメラ接続に必要なナビゲーション配線が、オプション設定もしくはナビゲーションユニットに接続されていない場合があります。詳しくはディーラーにおたずねください。",
    "40": "別途、日産純正部品のカメラ接続＆外部入力ハーネス（型番：K6384-C9910）が必要です。K6384-C9910についてはディーラーにご確認下さい。"
};